✨ feature: add slack error monitoring
depromeet/praise-push-server pull request #28
Opened 2023-12-09 05:42 UTC by khsrla9806

- Resolve: #12 

<br>

### 🎯 Review Point
1. develop 서버와 prod 서버를 분리하기 위해서 @Value() 사용한 필드 주입
    ```java
    @Value("${slack.webhook-url:NoneWebHookUrl}")
    private String webHookUrl;
    ```
    - application.yml에 slack.webhook-url을 추가해줘야 합니다.
    - 만약 해당 값이 없을 때, Injection Error가 발생하기 때문에 기본 값(NoneWebHookUrl)을 설정해줬습니다.

2. Slack Message를 만들고, 보내는 과정에서 에러가 생겨 시스템이 멈추면 안되기 때문에 try-catch를 이용한 핸들링
    ```java
    private void pushSlackErrorMessage(final Exception exception, final HttpServletRequest request) {
            try {
                SlackAttachment slackAttachment = new SlackAttachment();
                slackAttachment.setFallback("Error");
                slackAttachment.setColor("danger");
                slackAttachment.setTitle("5xx Error Detected");
                slackAttachment.setTitleLink(request.getContextPath());
                slackAttachment.setText(Arrays.toString(exception.getStackTrace()));
                slackAttachment.setFields(getSlackMessageFields(request));
    
                SlackMessage slackMessage = new SlackMessage();
                slackMessage.setAttachments(List.of(slackAttachment));
                slackMessage.setIcon(":rotating_light:");
                slackMessage.setText("5xx Error Detected");
                slackMessage.setUsername("Praise-Push Back End Developers");
    
                SlackApi slackApi = new SlackApi(webHookUrl);
                slackApi.call(slackMessage);
            } catch (SlackException ignored) {}
        }
    ```
    - try-catch로 Slack에서 에러가 난 경우 에러를 무시하도록 설정
    - Why? Slack 메시지를 못 보내는 것 때문에 다른 로직에 영향을 주면 안되기 때문에 이렇게 설정했습니다.

2023-12-12 13:23 UTC, yunyoung1819 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +    private void pushSlackErrorMessage(final Exception exception, final HttpServletRequest request) {
별도의 ErrorMonitoringProvider를 인터페이스로 만들어서 해당 인터페이스를 구현한 SlackErrorMonitoringProvider로 만들면 좋을 것 같습니다.

2023-12-12 13:40 UTC, yunyoung1819 requested changes
리뷰 남겨놓았습니다

2023-12-12 13:40 UTC, yunyoung1819 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +    private List<SlackField> getSlackMessageFields(HttpServletRequest request) {
해당 로직은 슬랙의 메시지 포멧을 만드는 것이므로 GlobalExceptionHandler의 책임이 아니라 별도의 Slack Message Format을 만드는 클래스로 분리하는 것이 좋을 것 같습니다. 또한 ExceptionHandler가 지금 하나지만 모든 Exception Handler마다 해당 메서드가 중복해서 들어간다면 슬랙의 알림 메시지 포멧을 변경하고 싶을 때 일일이 모든 Exception을 뒤져서 변경해주어야 합니다.

2023-12-12 13:40 UTC, yunyoung1819 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +            slackAttachment.setFallback("Error");
setter는 가능하면 사용하지 않는 것이 좋습니다.
setter를 열어두는 경우 setter를 사용해서 변경할 수 있기 때문에 추후 애플리케이션 규모가 커질수록 변경점을 찾기 어렵습니다.
그리고 만약 쓴다면 builder를 사용하는 것이 더 좋습니다.

2023-12-12 13:43 UTC, yunyoung1819 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +    private List<SlackField> getSlackMessageFields(HttpServletRequest request) {
메서드명은 getSlackMessageFields()이여서 조회해오는 것으로 알았는데 실제 내용은 set이여서 혼동을 주는 것 같습니다. 메서드명과 행위가 다른 것은 혼동이 되기 쉬워서 변경하면 좋을 것 같아요~

2023-12-12 13:45 UTC, yunyoung1819 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +            slackApi.call(slackMessage);
위의 메서드명은 push인데 여기에서 전부 처리안하고 별도 객체를 만들어서 다시 메서드를 호출하신 이유가 궁금합니다.

2023-12-12 13:57 UTC, khsrla9806 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +    @Value("${slack.webhook-url:NoneWebHookUrl}")
음 저도 `:`는 처음 써보는데, application.yml에 slack.webhook-url이 없는 경우 Bean 생성에 에러가 생겨서 찾아보니 application.yml에 `slack.webhook-url`이라는 값이 없는 경우 Default 값을 설정할 수 있는 방법이라고 해서 한번 써봤습니다.

그럼 반드시 application.yml에 `slack.webhook-url`이 있다는 가정하에 `:`를 그냥 빼보도록 하겠습니다!

2023-12-12 14:00 UTC, khsrla9806 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +            slackAttachment.setFallback("Error");
음 slack api dependency에서 제공하는 setter여서 사용을 해봤는데, 다른 방법이 있는지도 한번 찾아서 변경해보겠습니다.

2023-12-12 14:03 UTC, khsrla9806 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +        } catch (SlackException ignored) {}
Error 로그를 남기는 로직에서 Error가 발생했을 때, 어떤 행위를 취해줘야 할지 고민을 하다가 일단 비워둔 상태입니다.

5xx Exception이 발생해서 Slack으로 에러 알림을 보내려고 하는데, 이 Slack에서 예외가 발생한 경우에는 어떤 예외처리를 하면 좋을까요??

2023-12-12 14:06 UTC, khsrla9806 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +            slackApi.call(slackMessage);
별도 객체가 혹시 `SlackApi`를 말씀하시는 걸까요??

2023-12-12 15:07 UTC, khsrla9806 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +        } catch (SlackException ignored) {}
사용되지 않는 try-catch 구문 제거해서 반영했습니다!

2023-12-12 15:09 UTC, khsrla9806 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +            slackAttachment.setFallback("Error");
```java
/**
 * @return Slack error message with exception and request
 */
private SlackMessage getSlackMessage(final Exception exception, final HttpServletRequest request) {
    return new SlackMessage()
            .setUsername("Praise-Push Error Monitoring Bot")
            .setText("5xx Error is Detected")
            .setAttachments(getSlackAttachments(exception, request))
            .setIcon(":rotating_light:");
}
```

Slack Dependency에서 제공되는 setter여서 Builder는 따로 제공되지 않는 것 같습니다.

그래서 말씀 주신대로 ErrorMonitoringProvider를 인터페이스로 분리하고, 최대한 ExceptionHandler에서 현재 사용하고 있는 에러 모니터링 플랫폼(슬랙)이 무엇인지 모르게 의존성을 분리하는 작업을 진행해서 반영했습니다!

2023-12-12 15:11 UTC, khsrla9806 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +    private List<SlackField> getSlackMessageFields(HttpServletRequest request) {
음 SlackMessageField를 반환하는 것은 맞지만, 메서드 내부에서 반환하기 위한 SlackMessageField를 생성하는데 쓰이는 setter여서 이 부분을 어떻게 분리해야할지 감이 오지 않습니다. `makeSlackMessageFields()` 이런식으로 네이밍을 바꾸는건 괜찮을까요?

2023-12-12 15:12 UTC, khsrla9806 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +    private void pushSlackErrorMessage(final Exception exception, final HttpServletRequest request) {
별도의 ErrorMonitoringProvider 인터페이스를 만들고, 이를 구현하는 SlackErrorMonitoringProvider를 만들어서 반영해뒀습니다! 🤓

2023-12-12 15:14 UTC, khsrla9806 commented on src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
> +    @Value("${slack.webhook-url:NoneWebHookUrl}")
```java
public class SlackErrorMonitoringProvider implements ErrorMonitoringProvider {

    @Value("${error.webhook.url}")
    private String webHookUrl;

    ...
}
```

`:` 제거하고, `slack.webhook-url`에서 `error.webhook.url`로 변경해서 반영했습니다!

말씀하신 것 처럼 에러 모니터링 플랫폼을 뭐 쓸지 모르는 상황에서 `slack.webhook`보다는 `error.webhook`으로 하는 것이 더 확장성 있어 보이는 것 같아서 변경했습니다! 🤓

2023-12-13 15:14 UTC, khsrla9806 commented
@mywnajsldkf 환경 설정 끝나고 코멘트 주시면 바로 Merge 하겠습니다! 🤓

2023-12-19 05:34 UTC, merged