image upload interface
depromeet/praise-push-server pull request #47
Opened 2024-01-03 13:30 UTC by mywnajsldkf

2024-01-07 14:33 UTC, khsrla9806 requested changes
처음해보시는거일텐데 문서 찾아보고 하시느냐고 수고하셨습니다!! 🔥

2024-01-07 14:33 UTC, khsrla9806 commented on src/main/java/com/praise/push/adapter/out/persistence/ImagePersistenceAdapter.java
> +public class ImagePersistenceAdapter implements RecordImagePort {
여기도 원래 하던대로 public 접근제한자에서 default로 해서 통일시키는건 어떨까요??

2024-01-07 14:33 UTC, khsrla9806 commented on src/main/java/com/praise/push/adapter/out/persistence/ImagePersistenceAdapter.java
> +            uploadFileUrl = endPoint + bucket + "/" + fileName;
`end-point`는 "https://kr.object.ncloudstorage.com"이고, `bucket`은 "praise-up-image"인데, 이 사이에는 혹시 구분자("/")같은 것은 필요없나요?

그대로 합쳐버리면 "https://kr.object.ncloudstorage.compraise-up-image"으로 될거 같아서 의도하신 부분이 맞는지 궁금합니다!

2024-01-07 14:33 UTC, khsrla9806 commented on src/main/java/com/praise/push/adapter/out/persistence/ImagePersistenceAdapter.java
> +            e.printStackTrace();
이 부분은 printStackTrace로 처리하는 것 보다 Logger로 로그를 남기거나, RuntimeException으로 바꿔서 던지도록 해서 Slack으로 모니터링할 수 있도록 처리해보는 건 어떻게 생각하시나요? 의견입니다! 🤓

2024-01-07 14:33 UTC, khsrla9806 commented on src/main/java/com/praise/push/adapter/out/persistence/ImagePersistenceAdapter.java
> +        if (size >= MAX_FILE_SIZE) {
1MB까지 가능한거라면 `>=` 보다는 `>`이 적절할 것 같다는 생각이 드는데, 혹시 `=`까지 넣으신 의도가 있으신가요??

2024-01-08 00:57 UTC, mywnajsldkf commented on src/main/java/com/praise/push/adapter/out/persistence/ImagePersistenceAdapter.java
> +            uploadFileUrl = endPoint + bucket + "/" + fileName;
@khsrla9806 추가해야할 것 같아요! 감사합니다.

2024-01-08 01:04 UTC, mywnajsldkf commented on src/main/java/com/praise/push/adapter/out/persistence/ImagePersistenceAdapter.java
> +            e.printStackTrace();
@khsrla9806 
리뷰 감사합니다~ 일단 printStackTrace를 사용하는 것은 지양하는게 좋겠네요. ([참고](https://velog.io/@choiys0212/Throwable.printStackTrace%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0))

exception을 던져서 모니터링하는 방법이 좋을 것 같습니다~

2024-01-08 01:06 UTC, mywnajsldkf commented on src/main/java/com/praise/push/adapter/out/persistence/ImagePersistenceAdapter.java
> +        if (size >= MAX_FILE_SIZE) {
@khsrla9806 앗!!! 수정하겠습니다~

2024-01-08 01:40 UTC, khsrla9806 approved these changes

2024-01-10 13:11 UTC, merged